<?php
/**
 * Mapa completo de ladas de México con sus estados y ciudades correspondientes
 * Fuente: Instituto Federal de Telecomunicaciones (IFT)
 * Este archivo contiene TODAS las ladas de México organizadas por estado
 */

$MEXICO_LADAS = [
    // ======== AGUASCALIENTES ========
    '449' => ['estado' => 'Aguascalientes', 'region' => 'Centro', 'ciudad' => 'Aguascalientes'],
    '465' => ['estado' => 'Aguascalientes', 'region' => 'Centro', 'ciudad' => 'Rincón de Romos'],
    '496' => ['estado' => 'Aguascalientes', 'region' => 'Centro', 'ciudad' => 'Calvillo'],
    '458' => ['estado' => 'Aguascalientes', 'region' => 'Centro', 'ciudad' => 'Pabellón de Arteaga'],
    
    // ======== BAJA CALIFORNIA ========
    '664' => ['estado' => 'Baja California', 'region' => 'Noroeste', 'ciudad' => 'Tijuana'],
    '686' => ['estado' => 'Baja California', 'region' => 'Noroeste', 'ciudad' => 'Mexicali'],
    '646' => ['estado' => 'Baja California', 'region' => 'Noroeste', 'ciudad' => 'Ensenada'],
    '661' => ['estado' => 'Baja California', 'region' => 'Noroeste', 'ciudad' => 'Tecate'],
    '653' => ['estado' => 'Baja California', 'region' => 'Noroeste', 'ciudad' => 'San Felipe'],
    '665' => ['estado' => 'Baja California', 'region' => 'Noroeste', 'ciudad' => 'Playas de Rosarito'],
    '658' => ['estado' => 'Baja California', 'region' => 'Noroeste', 'ciudad' => 'San Quintín'],
    
    // ======== BAJA CALIFORNIA SUR ========
    '612' => ['estado' => 'Baja California Sur', 'region' => 'Noroeste', 'ciudad' => 'La Paz'],
    '624' => ['estado' => 'Baja California Sur', 'region' => 'Noroeste', 'ciudad' => 'Los Cabos'],
    '613' => ['estado' => 'Baja California Sur', 'region' => 'Noroeste', 'ciudad' => 'Santa Rosalía'],
    '615' => ['estado' => 'Baja California Sur', 'region' => 'Noroeste', 'ciudad' => 'Loreto'],
    '616' => ['estado' => 'Baja California Sur', 'region' => 'Noroeste', 'ciudad' => 'Ciudad Constitución'],
    '622' => ['estado' => 'Baja California Sur', 'region' => 'Noroeste', 'ciudad' => 'Guerrero Negro'],
    
    // ======== CAMPECHE ========
    '981' => ['estado' => 'Campeche', 'region' => 'Sureste', 'ciudad' => 'Campeche'],
    '938' => ['estado' => 'Campeche', 'region' => 'Sureste', 'ciudad' => 'Ciudad del Carmen'],
    '982' => ['estado' => 'Campeche', 'region' => 'Sureste', 'ciudad' => 'Champotón'],
    '913' => ['estado' => 'Campeche', 'region' => 'Sureste', 'ciudad' => 'Escárcega'],
    '983' => ['estado' => 'Campeche', 'region' => 'Sureste', 'ciudad' => 'Calakmul'],
    '916' => ['estado' => 'Campeche', 'region' => 'Sureste', 'ciudad' => 'Candelaria'],
    
    // ======== CHIAPAS ========
    '961' => ['estado' => 'Chiapas', 'region' => 'Sur', 'ciudad' => 'Tuxtla Gutiérrez'],
    '962' => ['estado' => 'Chiapas', 'region' => 'Sur', 'ciudad' => 'Tapachula'],
    '963' => ['estado' => 'Chiapas', 'region' => 'Sur', 'ciudad' => 'Comitán'],
    '964' => ['estado' => 'Chiapas', 'region' => 'Sur', 'ciudad' => 'Pichucalco'],
    '965' => ['estado' => 'Chiapas', 'region' => 'Sur', 'ciudad' => 'San Cristóbal de las Casas'],
    '966' => ['estado' => 'Chiapas', 'region' => 'Sur', 'ciudad' => 'Palenque'],
    '967' => ['estado' => 'Chiapas', 'region' => 'Sur', 'ciudad' => 'Cintalapa'],
    '968' => ['estado' => 'Chiapas', 'region' => 'Sur', 'ciudad' => 'Tonalá'],
    '919' => ['estado' => 'Chiapas', 'region' => 'Sur', 'ciudad' => 'Ocosingo'],
    '992' => ['estado' => 'Chiapas', 'region' => 'Sur', 'ciudad' => 'Motozintla'],
    '932' => ['estado' => 'Chiapas', 'region' => 'Sur', 'ciudad' => 'Villaflores'],
    '934' => ['estado' => 'Chiapas', 'region' => 'Sur', 'ciudad' => 'Huixtla'],
    
    // ======== CHIHUAHUA ========
    '614' => ['estado' => 'Chihuahua', 'region' => 'Norte', 'ciudad' => 'Chihuahua'],
    '656' => ['estado' => 'Chihuahua', 'region' => 'Norte', 'ciudad' => 'Ciudad Juárez'],
    '626' => ['estado' => 'Chihuahua', 'region' => 'Norte', 'ciudad' => 'Cuauhtémoc'],
    '627' => ['estado' => 'Chihuahua', 'region' => 'Norte', 'ciudad' => 'Parral'],
    '628' => ['estado' => 'Chihuahua', 'region' => 'Norte', 'ciudad' => 'Delicias'],
    '621' => ['estado' => 'Chihuahua', 'region' => 'Norte', 'ciudad' => 'Casas Grandes'],
    '629' => ['estado' => 'Chihuahua', 'region' => 'Norte', 'ciudad' => 'Camargo'],
    '635' => ['estado' => 'Chihuahua', 'region' => 'Norte', 'ciudad' => 'Madera'],
    '636' => ['estado' => 'Chihuahua', 'region' => 'Norte', 'ciudad' => 'Nuevo Casas Grandes'],
    '639' => ['estado' => 'Chihuahua', 'region' => 'Norte', 'ciudad' => 'Jiménez'],
    '648' => ['estado' => 'Chihuahua', 'region' => 'Norte', 'ciudad' => 'Ojinaga'],
    '652' => ['estado' => 'Chihuahua', 'region' => 'Norte', 'ciudad' => 'Guachochi'],
    '659' => ['estado' => 'Chihuahua', 'region' => 'Norte', 'ciudad' => 'Ocampo'],
    
    // ======== COAHUILA ========
    '844' => ['estado' => 'Coahuila', 'region' => 'Norte', 'ciudad' => 'Saltillo'],
    '871' => ['estado' => 'Coahuila', 'region' => 'Norte', 'ciudad' => 'Torreón'],
    '866' => ['estado' => 'Coahuila', 'region' => 'Norte', 'ciudad' => 'Piedras Negras'],
    '861' => ['estado' => 'Coahuila', 'region' => 'Norte', 'ciudad' => 'Sabinas'],
    '864' => ['estado' => 'Coahuila', 'region' => 'Norte', 'ciudad' => 'Nueva Rosita'],
    '869' => ['estado' => 'Coahuila', 'region' => 'Norte', 'ciudad' => 'Allende'],
    '872' => ['estado' => 'Coahuila', 'region' => 'Norte', 'ciudad' => 'Francisco I. Madero'],
    '873' => ['estado' => 'Coahuila', 'region' => 'Norte', 'ciudad' => 'Parras de la Fuente'],
    '877' => ['estado' => 'Coahuila', 'region' => 'Norte', 'ciudad' => 'Acuña'],
    '878' => ['estado' => 'Coahuila', 'region' => 'Norte', 'ciudad' => 'Monclova'],
    
    // ======== COLIMA ========
    '312' => ['estado' => 'Colima', 'region' => 'Occidente', 'ciudad' => 'Colima'],
    '313' => ['estado' => 'Colima', 'region' => 'Occidente', 'ciudad' => 'Manzanillo'],
    '314' => ['estado' => 'Colima', 'region' => 'Occidente', 'ciudad' => 'Tecomán'],
    '317' => ['estado' => 'Colima', 'region' => 'Occidente', 'ciudad' => 'Minatitlán'],
    
    // ======== CIUDAD DE MÉXICO ========
    '55' => ['estado' => 'Ciudad de México', 'region' => 'Centro', 'ciudad' => 'Ciudad de México'],
    
    // ======== DURANGO ========
    '618' => ['estado' => 'Durango', 'region' => 'Norte', 'ciudad' => 'Durango'],
    '671' => ['estado' => 'Durango', 'region' => 'Norte', 'ciudad' => 'Vicente Guerrero'],
    '674' => ['estado' => 'Durango', 'region' => 'Norte', 'ciudad' => 'Santiago Papasquiaro'],
    '675' => ['estado' => 'Durango', 'region' => 'Norte', 'ciudad' => 'Gómez Palacio'],
    '676' => ['estado' => 'Durango', 'region' => 'Norte', 'ciudad' => 'Santa María del Oro'],
    '677' => ['estado' => 'Durango', 'region' => 'Norte', 'ciudad' => 'Pueblo Nuevo'],
    '649' => ['estado' => 'Durango', 'region' => 'Norte', 'ciudad' => 'El Salto'],
    '872' => ['estado' => 'Durango', 'region' => 'Norte', 'ciudad' => 'Ceballos'],
    
    // ======== ESTADO DE MÉXICO ========
    '55' => ['estado' => 'Estado de México', 'region' => 'Centro', 'ciudad' => 'Zona Metropolitana'],
    '722' => ['estado' => 'Estado de México', 'region' => 'Centro', 'ciudad' => 'Toluca'],
    '712' => ['estado' => 'Estado de México', 'region' => 'Centro', 'ciudad' => 'Atlacomulco'],
    '714' => ['estado' => 'Estado de México', 'region' => 'Centro', 'ciudad' => 'Jilotepec'],
    '716' => ['estado' => 'Estado de México', 'region' => 'Centro', 'ciudad' => 'Ixtapan de la Sal'],
    '717' => ['estado' => 'Estado de México', 'region' => 'Centro', 'ciudad' => 'Tejupilco'],
    '719' => ['estado' => 'Estado de México', 'region' => 'Centro', 'ciudad' => 'Valle de Bravo'],
    '721' => ['estado' => 'Estado de México', 'region' => 'Centro', 'ciudad' => 'Tenango del Valle'],
    '724' => ['estado' => 'Estado de México', 'region' => 'Centro', 'ciudad' => 'Amecameca'],
    '593' => ['estado' => 'Estado de México', 'region' => 'Centro', 'ciudad' => 'Zumpango'],
    '594' => ['estado' => 'Estado de México', 'region' => 'Centro', 'ciudad' => 'Texcoco'],
    '595' => ['estado' => 'Estado de México', 'region' => 'Centro', 'ciudad' => 'Teotihuacán'],
    '596' => ['estado' => 'Estado de México', 'region' => 'Centro', 'ciudad' => 'Otumba'],
    '597' => ['estado' => 'Estado de México', 'region' => 'Centro', 'ciudad' => 'Temascalapa'],
    '588' => ['estado' => 'Estado de México', 'region' => 'Centro', 'ciudad' => 'Coatepec Harinas'],
    '711' => ['estado' => 'Estado de México', 'region' => 'Centro', 'ciudad' => 'El Oro'],
    '726' => ['estado' => 'Estado de México', 'region' => 'Centro', 'ciudad' => 'Chalco'],
    '728' => ['estado' => 'Estado de México', 'region' => 'Centro', 'ciudad' => 'Malinalco'],
    
    // ======== GUANAJUATO ========
    '477' => ['estado' => 'Guanajuato', 'region' => 'Centro', 'ciudad' => 'León'],
    '461' => ['estado' => 'Guanajuato', 'region' => 'Centro', 'ciudad' => 'Celaya'],
    '462' => ['estado' => 'Guanajuato', 'region' => 'Centro', 'ciudad' => 'Irapuato'],
    '411' => ['estado' => 'Guanajuato', 'region' => 'Centro', 'ciudad' => 'Guanajuato'],
    '412' => ['estado' => 'Guanajuato', 'region' => 'Centro', 'ciudad' => 'Dolores Hidalgo'],
    '413' => ['estado' => 'Guanajuato', 'region' => 'Centro', 'ciudad' => 'Acámbaro'],
    '415' => ['estado' => 'Guanajuato', 'region' => 'Centro', 'ciudad' => 'San Miguel de Allende'],
    '417' => ['estado' => 'Guanajuato', 'region' => 'Centro', 'ciudad' => 'San Luis de la Paz'],
    '418' => ['estado' => 'Guanajuato', 'region' => 'Centro', 'ciudad' => 'Pénjamo'],
    '419' => ['estado' => 'Guanajuato', 'region' => 'Centro', 'ciudad' => 'San José Iturbide'],
    '421' => ['estado' => 'Guanajuato', 'region' => 'Centro', 'ciudad' => 'San Francisco del Rincón'],
    '429' => ['estado' => 'Guanajuato', 'region' => 'Centro', 'ciudad' => 'Jerécuaro'],
    '432' => ['estado' => 'Guanajuato', 'region' => 'Centro', 'ciudad' => 'Uriangato'],
    '445' => ['estado' => 'Guanajuato', 'region' => 'Centro', 'ciudad' => 'Yuriria'],
    '464' => ['estado' => 'Guanajuato', 'region' => 'Centro', 'ciudad' => 'Salvatierra'],
    '466' => ['estado' => 'Guanajuato', 'region' => 'Centro', 'ciudad' => 'Salamanca'],
    '468' => ['estado' => 'Guanajuato', 'region' => 'Centro', 'ciudad' => 'Valle de Santiago'],
    '469' => ['estado' => 'Guanajuato', 'region' => 'Centro', 'ciudad' => 'Silao'],
    '476' => ['estado' => 'Guanajuato', 'region' => 'Centro', 'ciudad' => 'San Felipe'],
    
    // ======== GUERRERO ========
    '744' => ['estado' => 'Guerrero', 'region' => 'Sur', 'ciudad' => 'Acapulco'],
    '747' => ['estado' => 'Guerrero', 'region' => 'Sur', 'ciudad' => 'Chilpancingo'],
    '733' => ['estado' => 'Guerrero', 'region' => 'Sur', 'ciudad' => 'Iguala'],
    '742' => ['estado' => 'Guerrero', 'region' => 'Sur', 'ciudad' => 'Zihuatanejo'],
    '745' => ['estado' => 'Guerrero', 'region' => 'Sur', 'ciudad' => 'Taxco'],
    '732' => ['estado' => 'Guerrero', 'region' => 'Sur', 'ciudad' => 'Arcelia'],
    '736' => ['estado' => 'Guerrero', 'region' => 'Sur', 'ciudad' => 'Ciudad Altamirano'],
    '737' => ['estado' => 'Guerrero', 'region' => 'Sur', 'ciudad' => 'Coyuca de Catalán'],
    '741' => ['estado' => 'Guerrero', 'region' => 'Sur', 'ciudad' => 'Atoyac de Álvarez'],
    '748' => ['estado' => 'Guerrero', 'region' => 'Sur', 'ciudad' => 'Tlapa'],
    '781' => ['estado' => 'Guerrero', 'region' => 'Sur', 'ciudad' => 'Ciudad de Huitzuco'],
    
    // ======== HIDALGO ========
    '771' => ['estado' => 'Hidalgo', 'region' => 'Centro', 'ciudad' => 'Pachuca'],
    '743' => ['estado' => 'Hidalgo', 'region' => 'Centro', 'ciudad' => 'Huejutla'],
    '748' => ['estado' => 'Hidalgo', 'region' => 'Centro', 'ciudad' => 'Zimapán'],
    '759' => ['estado' => 'Hidalgo', 'region' => 'Centro', 'ciudad' => 'Tepeji del Río'],
    '761' => ['estado' => 'Hidalgo', 'region' => 'Centro', 'ciudad' => 'Actopan'],
    '763' => ['estado' => 'Hidalgo', 'region' => 'Centro', 'ciudad' => 'Ixmiquilpan'],
    '764' => ['estado' => 'Hidalgo', 'region' => 'Centro', 'ciudad' => 'Zacualtipán'],
    '768' => ['estado' => 'Hidalgo', 'region' => 'Centro', 'ciudad' => 'Tizayuca'],
    '769' => ['estado' => 'Hidalgo', 'region' => 'Centro', 'ciudad' => 'Apan'],
    '770' => ['estado' => 'Hidalgo', 'region' => 'Centro', 'ciudad' => 'Tulancingo'],
    '772' => ['estado' => 'Hidalgo', 'region' => 'Centro', 'ciudad' => 'Tula'],
    '773' => ['estado' => 'Hidalgo', 'region' => 'Centro', 'ciudad' => 'Tepeapulco'],
    '774' => ['estado' => 'Hidalgo', 'region' => 'Centro', 'ciudad' => 'Huichapan'],
    '775' => ['estado' => 'Hidalgo', 'region' => 'Centro', 'ciudad' => 'Metztitlán'],
    '776' => ['estado' => 'Hidalgo', 'region' => 'Centro', 'ciudad' => 'Atotonilco el Grande'],
    '778' => ['estado' => 'Hidalgo', 'region' => 'Centro', 'ciudad' => 'San Bartolo Tutotepec'],
    '789' => ['estado' => 'Hidalgo', 'region' => 'Centro', 'ciudad' => 'Tenango de Doria'],
    '791' => ['estado' => 'Hidalgo', 'region' => 'Centro', 'ciudad' => 'Mineral del Monte'],
    
    // ======== JALISCO ========
    '33' => ['estado' => 'Jalisco', 'region' => 'Occidente', 'ciudad' => 'Guadalajara'],
    '316' => ['estado' => 'Jalisco', 'region' => 'Occidente', 'ciudad' => 'Cihuatlán'],
    '322' => ['estado' => 'Jalisco', 'region' => 'Occidente', 'ciudad' => 'Puerto Vallarta'],
    '341' => ['estado' => 'Jalisco', 'region' => 'Occidente', 'ciudad' => 'Zapotlán El Grande'],
    '342' => ['estado' => 'Jalisco', 'region' => 'Occidente', 'ciudad' => 'Tequila'],
    '344' => ['estado' => 'Jalisco', 'region' => 'Occidente', 'ciudad' => 'Autlán de Navarro'],
    '346' => ['estado' => 'Jalisco', 'region' => 'Occidente', 'ciudad' => 'Tepatitlán'],
    '347' => ['estado' => 'Jalisco', 'region' => 'Occidente', 'ciudad' => 'San Juan de los Lagos'],
    '348' => ['estado' => 'Jalisco', 'region' => 'Occidente', 'ciudad' => 'Lagos de Moreno'],
    '349' => ['estado' => 'Jalisco', 'region' => 'Occidente', 'ciudad' => 'Tamazula de Gordiano'],
    '353' => ['estado' => 'Jalisco', 'region' => 'Occidente', 'ciudad' => 'Ocotlán'],
    '357' => ['estado' => 'Jalisco', 'region' => 'Occidente', 'ciudad' => 'Arandas'],
    '358' => ['estado' => 'Jalisco', 'region' => 'Occidente', 'ciudad' => 'Ameca'],
    '371' => ['estado' => 'Jalisco', 'region' => 'Occidente', 'ciudad' => 'Unión de San Antonio'],
    '372' => ['estado' => 'Jalisco', 'region' => 'Occidente', 'ciudad' => 'La Barca'],
    '373' => ['estado' => 'Jalisco', 'region' => 'Occidente', 'ciudad' => 'Atotonilco El Alto'],
    '374' => ['estado' => 'Jalisco', 'region' => 'Occidente', 'ciudad' => 'Sayula'],
    '375' => ['estado' => 'Jalisco', 'region' => 'Occidente', 'ciudad' => 'Mazamitla'],
    '377' => ['estado' => 'Jalisco', 'region' => 'Occidente', 'ciudad' => 'Yahualica'],
    '382' => ['estado' => 'Jalisco', 'region' => 'Occidente', 'ciudad' => 'Encarnación de Díaz'],
    '384' => ['estado' => 'Jalisco', 'region' => 'Occidente', 'ciudad' => 'Magdalena'],
    '385' => ['estado' => 'Jalisco', 'region' => 'Occidente', 'ciudad' => 'San Martín Hidalgo'],
    '386' => ['estado' => 'Jalisco', 'region' => 'Occidente', 'ciudad' => 'Mascota'],
    '387' => ['estado' => 'Jalisco', 'region' => 'Occidente', 'ciudad' => 'Colotlán'],
    '388' => ['estado' => 'Jalisco', 'region' => 'Occidente', 'ciudad' => 'Talpa de Allende'],
    
    // ======== MICHOACÁN ========
    '443' => ['estado' => 'Michoacán', 'region' => 'Occidente', 'ciudad' => 'Morelia'],
    '424' => ['estado' => 'Michoacán', 'region' => 'Occidente', 'ciudad' => 'Lázaro Cárdenas'],
    '425' => ['estado' => 'Michoacán', 'region' => 'Occidente', 'ciudad' => 'Maravatío'],
    '426' => ['estado' => 'Michoacán', 'region' => 'Occidente', 'ciudad' => 'Zitácuaro'],
    '434' => ['estado' => 'Michoacán', 'region' => 'Occidente', 'ciudad' => 'Los Reyes'],
    '435' => ['estado' => 'Michoacán', 'region' => 'Occidente', 'ciudad' => 'Pátzcuaro'],
    '438' => ['estado' => 'Michoacán', 'region' => 'Occidente', 'ciudad' => 'Huetamo'],
    '451' => ['estado' => 'Michoacán', 'region' => 'Occidente', 'ciudad' => 'Tacámbaro'],
    '452' => ['estado' => 'Michoacán', 'region' => 'Occidente', 'ciudad' => 'Uruapan'],
    '453' => ['estado' => 'Michoacán', 'region' => 'Occidente', 'ciudad' => 'Apatzingán'],
    '455' => ['estado' => 'Michoacán', 'region' => 'Occidente', 'ciudad' => 'Sahuayo'],
    '456' => ['estado' => 'Michoacán', 'region' => 'Occidente', 'ciudad' => 'Ciudad Hidalgo'],
    '457' => ['estado' => 'Michoacán', 'region' => 'Occidente', 'ciudad' => 'Jiquilpan'],
    '459' => ['estado' => 'Michoacán', 'region' => 'Occidente', 'ciudad' => 'La Piedad'],
    '786' => ['estado' => 'Michoacán', 'region' => 'Occidente', 'ciudad' => 'Zamora'],
    
    // ======== MORELOS ========
    '777' => ['estado' => 'Morelos', 'region' => 'Centro', 'ciudad' => 'Cuernavaca'],
    '731' => ['estado' => 'Morelos', 'region' => 'Centro', 'ciudad' => 'Jojutla'],
    '735' => ['estado' => 'Morelos', 'region' => 'Centro', 'ciudad' => 'Cuautla'],
    '751' => ['estado' => 'Morelos', 'region' => 'Centro', 'ciudad' => 'Puente de Ixtla'],
    '734' => ['estado' => 'Morelos', 'region' => 'Centro', 'ciudad' => 'Tetecala'],
    '739' => ['estado' => 'Morelos', 'region' => 'Centro', 'ciudad' => 'Zacatepec'],
    
    // ======== NAYARIT ========
    '311' => ['estado' => 'Nayarit', 'region' => 'Occidente', 'ciudad' => 'Tepic'],
    '319' => ['estado' => 'Nayarit', 'region' => 'Occidente', 'ciudad' => 'Acaponeta'],
    '321' => ['estado' => 'Nayarit', 'region' => 'Occidente', 'ciudad' => 'Compostela'],
    '323' => ['estado' => 'Nayarit', 'region' => 'Occidente', 'ciudad' => 'Ruiz'],
    '324' => ['estado' => 'Nayarit', 'region' => 'Occidente', 'ciudad' => 'Santiago Ixcuintla'],
    '325' => ['estado' => 'Nayarit', 'region' => 'Occidente', 'ciudad' => 'San Blas'],
    '327' => ['estado' => 'Nayarit', 'region' => 'Occidente', 'ciudad' => 'Ixtlán del Río'],
    '329' => ['estado' => 'Nayarit', 'region' => 'Occidente', 'ciudad' => 'Bahía de Banderas'],
    
    // ======== NUEVO LEÓN ========
    '81' => ['estado' => 'Nuevo León', 'region' => 'Norte', 'ciudad' => 'Monterrey'],
    '821' => ['estado' => 'Nuevo León', 'region' => 'Norte', 'ciudad' => 'China'],
    '823' => ['estado' => 'Nuevo León', 'region' => 'Norte', 'ciudad' => 'Montemorelos'],
    '824' => ['estado' => 'Nuevo León', 'region' => 'Norte', 'ciudad' => 'Linares'],
    '825' => ['estado' => 'Nuevo León', 'region' => 'Norte', 'ciudad' => 'Cadereyta'],
    '826' => ['estado' => 'Nuevo León', 'region' => 'Norte', 'ciudad' => 'Doctor Arroyo'],
    '828' => ['estado' => 'Nuevo León', 'region' => 'Norte', 'ciudad' => 'Sabinas Hidalgo'],
    '829' => ['estado' => 'Nuevo León', 'region' => 'Norte', 'ciudad' => 'Anáhuac'],
    '842' => ['estado' => 'Nuevo León', 'region' => 'Norte', 'ciudad' => 'García'],

    // ======== OAXACA ========
    '951' => ['estado' => 'Oaxaca', 'region' => 'Sur', 'ciudad' => 'Oaxaca'],
    '953' => ['estado' => 'Oaxaca', 'region' => 'Sur', 'ciudad' => 'Puerto Escondido'],
    '954' => ['estado' => 'Oaxaca', 'region' => 'Sur', 'ciudad' => 'Pinotepa Nacional'],
    '955' => ['estado' => 'Oaxaca', 'region' => 'Sur', 'ciudad' => 'Tehuantepec'],
    '958' => ['estado' => 'Oaxaca', 'region' => 'Sur', 'ciudad' => 'Huajuapan de León'],
    '971' => ['estado' => 'Oaxaca', 'region' => 'Sur', 'ciudad' => 'Matías Romero'],
    '972' => ['estado' => 'Oaxaca', 'region' => 'Sur', 'ciudad' => 'Loma Bonita'],
    '981' => ['estado' => 'Oaxaca', 'region' => 'Sur', 'ciudad' => 'Tuxtepec'],
    '994' => ['estado' => 'Oaxaca', 'region' => 'Sur', 'ciudad' => 'Juchitán'],
    '995' => ['estado' => 'Oaxaca', 'region' => 'Sur', 'ciudad' => 'Salina Cruz'],
    '996' => ['estado' => 'Oaxaca', 'region' => 'Sur', 'ciudad' => 'Huatulco'],
    '997' => ['estado' => 'Oaxaca', 'region' => 'Sur', 'ciudad' => 'Miahuatlán'],
    '991' => ['estado' => 'Oaxaca', 'region' => 'Sur', 'ciudad' => 'Tlaxiaco'],

    // ======== PUEBLA ========
    '222' => ['estado' => 'Puebla', 'region' => 'Centro', 'ciudad' => 'Puebla'],
    '231' => ['estado' => 'Puebla', 'region' => 'Centro', 'ciudad' => 'Atlixco'],
    '233' => ['estado' => 'Puebla', 'region' => 'Centro', 'ciudad' => 'Izúcar de Matamoros'],
    '236' => ['estado' => 'Puebla', 'region' => 'Centro', 'ciudad' => 'Tehuacán'],
    '237' => ['estado' => 'Puebla', 'region' => 'Centro', 'ciudad' => 'Teziutlán'],
    '238' => ['estado' => 'Puebla', 'region' => 'Centro', 'ciudad' => 'Zacapoaxtla'],
    '243' => ['estado' => 'Puebla', 'region' => 'Centro', 'ciudad' => 'Acatlán'],
    '244' => ['estado' => 'Puebla', 'region' => 'Centro', 'ciudad' => 'Huauchinango'],
    '245' => ['estado' => 'Puebla', 'region' => 'Centro', 'ciudad' => 'Tecamachalco'],
    '248' => ['estado' => 'Puebla', 'region' => 'Centro', 'ciudad' => 'Libres'],
    '249' => ['estado' => 'Puebla', 'region' => 'Centro', 'ciudad' => 'San Martín Texmelucan'],
    '232' => ['estado' => 'Puebla', 'region' => 'Centro', 'ciudad' => 'Acatzingo'],
    '275' => ['estado' => 'Puebla', 'region' => 'Centro', 'ciudad' => 'Ciudad Serdán'],
    '276' => ['estado' => 'Puebla', 'region' => 'Centro', 'ciudad' => 'Xicotepec'],
    '282' => ['estado' => 'Puebla', 'region' => 'Centro', 'ciudad' => 'Zacatlán'],
    
    // ======== QUERÉTARO ========
    '442' => ['estado' => 'Querétaro', 'region' => 'Centro', 'ciudad' => 'Querétaro'],
    '414' => ['estado' => 'Querétaro', 'region' => 'Centro', 'ciudad' => 'San Juan del Río'],
    '419' => ['estado' => 'Querétaro', 'region' => 'Centro', 'ciudad' => 'Tequisquiapan'],
    '427' => ['estado' => 'Querétaro', 'region' => 'Centro', 'ciudad' => 'Cadereyta'],
    '441' => ['estado' => 'Querétaro', 'region' => 'Centro', 'ciudad' => 'Colón'],
    '448' => ['estado' => 'Querétaro', 'region' => 'Centro', 'ciudad' => 'Jalpan de Serra'],

    // ======== QUINTANA ROO ========
    '998' => ['estado' => 'Quintana Roo', 'region' => 'Sureste', 'ciudad' => 'Cancún'],
    '983' => ['estado' => 'Quintana Roo', 'region' => 'Sureste', 'ciudad' => 'Chetumal'],
    '984' => ['estado' => 'Quintana Roo', 'region' => 'Sureste', 'ciudad' => 'Playa del Carmen'],
    '987' => ['estado' => 'Quintana Roo', 'region' => 'Sureste', 'ciudad' => 'Cozumel'],
    '997' => ['estado' => 'Quintana Roo', 'region' => 'Sureste', 'ciudad' => 'Felipe Carrillo Puerto'],
    '985' => ['estado' => 'Quintana Roo', 'region' => 'Sureste', 'ciudad' => 'Tulum'],

    // ======== SAN LUIS POTOSÍ ========
    '444' => ['estado' => 'San Luis Potosí', 'region' => 'Centro', 'ciudad' => 'San Luis Potosí'],
    '481' => ['estado' => 'San Luis Potosí', 'region' => 'Centro', 'ciudad' => 'Matehuala'],
    '483' => ['estado' => 'San Luis Potosí', 'region' => 'Centro', 'ciudad' => 'Ciudad Valles'],
    '485' => ['estado' => 'San Luis Potosí', 'region' => 'Centro', 'ciudad' => 'Rioverde'],
    '486' => ['estado' => 'San Luis Potosí', 'region' => 'Centro', 'ciudad' => 'Tamazunchale'],
    '487' => ['estado' => 'San Luis Potosí', 'region' => 'Centro', 'ciudad' => 'Cerritos'],
    '488' => ['estado' => 'San Luis Potosí', 'region' => 'Centro', 'ciudad' => 'Villa de Arista'],
    '489' => ['estado' => 'San Luis Potosí', 'region' => 'Centro', 'ciudad' => 'Villa de Reyes'],
    '482' => ['estado' => 'San Luis Potosí', 'region' => 'Centro', 'ciudad' => 'Charcas'],
    '496' => ['estado' => 'San Luis Potosí', 'region' => 'Centro', 'ciudad' => 'Cárdenas'],

    // ======== SINALOA ========
    '667' => ['estado' => 'Sinaloa', 'region' => 'Noroeste', 'ciudad' => 'Culiacán'],
    '668' => ['estado' => 'Sinaloa', 'region' => 'Noroeste', 'ciudad' => 'Los Mochis'],
    '669' => ['estado' => 'Sinaloa', 'region' => 'Noroeste', 'ciudad' => 'Mazatlán'],
    '672' => ['estado' => 'Sinaloa', 'region' => 'Noroeste', 'ciudad' => 'Navolato'],
    '673' => ['estado' => 'Sinaloa', 'region' => 'Noroeste', 'ciudad' => 'Guasave'],
    '687' => ['estado' => 'Sinaloa', 'region' => 'Noroeste', 'ciudad' => 'Guamúchil'],
    '694' => ['estado' => 'Sinaloa', 'region' => 'Noroeste', 'ciudad' => 'Escuinapa'],
    '696' => ['estado' => 'Sinaloa', 'region' => 'Noroeste', 'ciudad' => 'El Fuerte'],
    '698' => ['estado' => 'Sinaloa', 'region' => 'Noroeste', 'ciudad' => 'El Rosario'],

    // ======== SONORA ========
    '662' => ['estado' => 'Sonora', 'region' => 'Noroeste', 'ciudad' => 'Hermosillo'],
    '622' => ['estado' => 'Sonora', 'region' => 'Noroeste', 'ciudad' => 'Ciudad Obregón'],
    '631' => ['estado' => 'Sonora', 'region' => 'Noroeste', 'ciudad' => 'Caborca'],
    '632' => ['estado' => 'Sonora', 'region' => 'Noroeste', 'ciudad' => 'Navojoa'],
    '633' => ['estado' => 'Sonora', 'region' => 'Noroeste', 'ciudad' => 'Cananea'],
    '634' => ['estado' => 'Sonora', 'region' => 'Noroeste', 'ciudad' => 'Guaymas'],
    '637' => ['estado' => 'Sonora', 'region' => 'Noroeste', 'ciudad' => 'Agua Prieta'],
    '638' => ['estado' => 'Sonora', 'region' => 'Noroeste', 'ciudad' => 'Huatabampo'],
    '641' => ['estado' => 'Sonora', 'region' => 'Noroeste', 'ciudad' => 'Puerto Peñasco'],
    '642' => ['estado' => 'Sonora', 'region' => 'Noroeste', 'ciudad' => 'Magdalena'],
    '643' => ['estado' => 'Sonora', 'region' => 'Noroeste', 'ciudad' => 'Nacozari'],
    '651' => ['estado' => 'Sonora', 'region' => 'Noroeste', 'ciudad' => 'Nogales'],
    '653' => ['estado' => 'Sonora', 'region' => 'Noroeste', 'ciudad' => 'San Luis Río Colorado'],

    // ======== TABASCO ========
    '993' => ['estado' => 'Tabasco', 'region' => 'Sureste', 'ciudad' => 'Villahermosa'],
    '913' => ['estado' => 'Tabasco', 'region' => 'Sureste', 'ciudad' => 'Cárdenas'],
    '914' => ['estado' => 'Tabasco', 'region' => 'Sureste', 'ciudad' => 'Comalcalco'],
    '917' => ['estado' => 'Tabasco', 'region' => 'Sureste', 'ciudad' => 'Tenosique'],
    '923' => ['estado' => 'Tabasco', 'region' => 'Sureste', 'ciudad' => 'Emiliano Zapata'],
    '924' => ['estado' => 'Tabasco', 'region' => 'Sureste', 'ciudad' => 'Frontera'],
    '932' => ['estado' => 'Tabasco', 'region' => 'Sureste', 'ciudad' => 'Teapa'],
    '933' => ['estado' => 'Tabasco', 'region' => 'Sureste', 'ciudad' => 'Macuspana'],
    '934' => ['estado' => 'Tabasco', 'region' => 'Sureste', 'ciudad' => 'Balancán'],
    '936' => ['estado' => 'Tabasco', 'region' => 'Sureste', 'ciudad' => 'Paraíso'],
    '937' => ['estado' => 'Tabasco', 'region' => 'Sureste', 'ciudad' => 'Huimanguillo'],

    // ======== TAMAULIPAS ========
    '833' => ['estado' => 'Tamaulipas', 'region' => 'Noreste', 'ciudad' => 'Tampico'],
    '834' => ['estado' => 'Tamaulipas', 'region' => 'Noreste', 'ciudad' => 'Ciudad Victoria'],
    '836' => ['estado' => 'Tamaulipas', 'region' => 'Noreste', 'ciudad' => 'San Fernando'],
    '841' => ['estado' => 'Tamaulipas', 'region' => 'Noreste', 'ciudad' => 'Aldama'],
    '864' => ['estado' => 'Tamaulipas', 'region' => 'Noreste', 'ciudad' => 'Miguel Alemán'],
    '866' => ['estado' => 'Tamaulipas', 'region' => 'Noreste', 'ciudad' => 'Ciudad Mante'],
    '867' => ['estado' => 'Tamaulipas', 'region' => 'Noreste', 'ciudad' => 'Nuevo Laredo'],
    '868' => ['estado' => 'Tamaulipas', 'region' => 'Noreste', 'ciudad' => 'Matamoros'],
    '891' => ['estado' => 'Tamaulipas', 'region' => 'Noreste', 'ciudad' => 'Valle Hermoso'],
    '894' => ['estado' => 'Tamaulipas', 'region' => 'Noreste', 'ciudad' => 'Río Bravo'],
    '897' => ['estado' => 'Tamaulipas', 'region' => 'Noreste', 'ciudad' => 'González'],
    '898' => ['estado' => 'Tamaulipas', 'region' => 'Noreste', 'ciudad' => 'Soto la Marina'],
    '899' => ['estado' => 'Tamaulipas', 'region' => 'Noreste', 'ciudad' => 'Reynosa'],

    // ======== TLAXCALA ========
    '246' => ['estado' => 'Tlaxcala', 'region' => 'Centro', 'ciudad' => 'Tlaxcala'],
    '241' => ['estado' => 'Tlaxcala', 'region' => 'Centro', 'ciudad' => 'Apizaco'],
    '222' => ['estado' => 'Tlaxcala', 'region' => 'Centro', 'ciudad' => 'Calpulalpan'],
    '224' => ['estado' => 'Tlaxcala', 'region' => 'Centro', 'ciudad' => 'Huamantla'],
    '247' => ['estado' => 'Tlaxcala', 'region' => 'Centro', 'ciudad' => 'Tlaxco'],
    '248' => ['estado' => 'Tlaxcala', 'region' => 'Centro', 'ciudad' => 'Zacatelco'],

    // ======== VERACRUZ ========
    '229' => ['estado' => 'Veracruz', 'region' => 'Golfo', 'ciudad' => 'Veracruz'],
    '228' => ['estado' => 'Veracruz', 'region' => 'Golfo', 'ciudad' => 'Xalapa'],
    '231' => ['estado' => 'Veracruz', 'region' => 'Golfo', 'ciudad' => 'Actopan'],
    '232' => ['estado' => 'Veracruz', 'region' => 'Golfo', 'ciudad' => 'Alvarado'],
    '233' => ['estado' => 'Veracruz', 'region' => 'Golfo', 'ciudad' => 'Santiago Tuxtla'],
    '234' => ['estado' => 'Veracruz', 'region' => 'Golfo', 'ciudad' => 'Coatepec'],
    '235' => ['estado' => 'Veracruz', 'region' => 'Golfo', 'ciudad' => 'Cosamaloapan'],
    '241' => ['estado' => 'Veracruz', 'region' => 'Golfo', 'ciudad' => 'Cerro Azul'],
    '245' => ['estado' => 'Veracruz', 'region' => 'Golfo', 'ciudad' => 'San Andrés Tuxtla'],
    '271' => ['estado' => 'Veracruz', 'region' => 'Golfo', 'ciudad' => 'Córdoba'],
    '272' => ['estado' => 'Veracruz', 'region' => 'Golfo', 'ciudad' => 'Orizaba'],
    '273' => ['estado' => 'Veracruz', 'region' => 'Golfo', 'ciudad' => 'Tierra Blanca'],
    '274' => ['estado' => 'Veracruz', 'region' => 'Golfo', 'ciudad' => 'Isla'],
    '275' => ['estado' => 'Veracruz', 'region' => 'Golfo', 'ciudad' => 'Cuitláhuac'],
    '276' => ['estado' => 'Veracruz', 'region' => 'Golfo', 'ciudad' => 'Acayucan'],
    '278' => ['estado' => 'Veracruz', 'region' => 'Golfo', 'ciudad' => 'Perote'],
    '279' => ['estado' => 'Veracruz', 'region' => 'Golfo', 'ciudad' => 'Huatusco'],
    '282' => ['estado' => 'Veracruz', 'region' => 'Golfo', 'ciudad' => 'Tantoyuca'],
    '283' => ['estado' => 'Veracruz', 'region' => 'Golfo', 'ciudad' => 'Naranjos'],
    '285' => ['estado' => 'Veracruz', 'region' => 'Golfo', 'ciudad' => 'Catemaco'],
    '287' => ['estado' => 'Veracruz', 'region' => 'Golfo', 'ciudad' => 'Papantla'],
    '294' => ['estado' => 'Veracruz', 'region' => 'Golfo', 'ciudad' => 'Martínez de la Torre'],
    '296' => ['estado' => 'Veracruz', 'region' => 'Golfo', 'ciudad' => 'Tuxpam'],
    '297' => ['estado' => 'Veracruz', 'region' => 'Golfo', 'ciudad' => 'Pánuco'],
    '746' => ['estado' => 'Veracruz', 'region' => 'Golfo', 'ciudad' => 'Paso del Macho'],
    '782' => ['estado' => 'Veracruz', 'region' => 'Golfo', 'ciudad' => 'Poza Rica'],
    '783' => ['estado' => 'Veracruz', 'region' => 'Golfo', 'ciudad' => 'Tuxpan'],
    '784' => ['estado' => 'Veracruz', 'region' => 'Golfo', 'ciudad' => 'Álamo'],
    '785' => ['estado' => 'Veracruz', 'region' => 'Golfo', 'ciudad' => 'Tempoal'],
    '786' => ['estado' => 'Veracruz', 'region' => 'Golfo', 'ciudad' => 'Chicontepec'],
    '789' => ['estado' => 'Veracruz', 'region' => 'Golfo', 'ciudad' => 'Huayacocotla'],
    '791' => ['estado' => 'Veracruz', 'region' => 'Golfo', 'ciudad' => 'Misantla'],
    '921' => ['estado' => 'Veracruz', 'region' => 'Golfo', 'ciudad' => 'Coatzacoalcos'],
    '922' => ['estado' => 'Veracruz', 'region' => 'Golfo', 'ciudad' => 'Minatitlán'],
    '923' => ['estado' => 'Veracruz', 'region' => 'Golfo', 'ciudad' => 'Las Choapas'],
    '924' => ['estado' => 'Veracruz', 'region' => 'Golfo', 'ciudad' => 'Jáltipan'],

    // ======== YUCATÁN ========
    '999' => ['estado' => 'Yucatán', 'region' => 'Sureste', 'ciudad' => 'Mérida'],
    '969' => ['estado' => 'Yucatán', 'region' => 'Sureste', 'ciudad' => 'Valladolid'],
    '985' => ['estado' => 'Yucatán', 'region' => 'Sureste', 'ciudad' => 'Ticul'],
    '986' => ['estado' => 'Yucatán', 'region' => 'Sureste', 'ciudad' => 'Tizimín'],
    '988' => ['estado' => 'Yucatán', 'region' => 'Sureste', 'ciudad' => 'Progreso'],
    '991' => ['estado' => 'Yucatán', 'region' => 'Sureste', 'ciudad' => 'Motul'],
    '992' => ['estado' => 'Yucatán', 'region' => 'Sureste', 'ciudad' => 'Tekax'],
    '997' => ['estado' => 'Yucatán', 'region' => 'Sureste', 'ciudad' => 'Izamal'],

    // ======== ZACATECAS ========
    '492' => ['estado' => 'Zacatecas', 'region' => 'Centro', 'ciudad' => 'Zacatecas'],
    '433' => ['estado' => 'Zacatecas', 'region' => 'Centro', 'ciudad' => 'Fresnillo'],
    '437' => ['estado' => 'Zacatecas', 'region' => 'Centro', 'ciudad' => 'Jalpa'],
    '457' => ['estado' => 'Zacatecas', 'region' => 'Centro', 'ciudad' => 'Nochistlán'],
    '458' => ['estado' => 'Zacatecas', 'region' => 'Centro', 'ciudad' => 'Ojocaliente'],
    '463' => ['estado' => 'Zacatecas', 'region' => 'Centro', 'ciudad' => 'Concepción del Oro'],
    '467' => ['estado' => 'Zacatecas', 'region' => 'Centro', 'ciudad' => 'Juan Aldama'],
    '494' => ['estado' => 'Zacatecas', 'region' => 'Centro', 'ciudad' => 'Jerez'],
    '496' => ['estado' => 'Zacatecas', 'region' => 'Centro', 'ciudad' => 'Valparaíso'],
    '498' => ['estado' => 'Zacatecas', 'region' => 'Centro', 'ciudad' => 'Río Grande'],
    '499' => ['estado' => 'Zacatecas', 'region' => 'Centro', 'ciudad' => 'Sombrerete'],
];